// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Login(arg1:string,arg2:string):Promise<string>;

export function SelectFile():Promise<string>;

export function WrapFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;
